spring:
  application:
    name: Enotes_API_Service
  profiles:
    active: dev
    
---
# dev config
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: roadie084@gmail.com
    password: sjsuulkaaracovar
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc 

server:
  port: 7001
file:
  upload:
    path: notes/
---
# test config
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: roadie084@gmail.com
    password: sjsuulkaaracovar
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc 
server:
  port: 7002      
file:
  upload:
    path: notes/
---
# uat config
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_uat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: roadie084@gmail.com
    password: sjsuulkaaracovar
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true 
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc 
server:
  port: 7001      
file:
  upload:
    path: notes/

---
# prod config
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: roadie084@gmail.com
    password: sjsuulkaaracovar
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true  
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc 
server:
  port: 7003     
file:
  upload:
    path: notes/
